# Generated by Django 3.1.1 on 2020-10-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='info',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
