# Generated by Django 3.1.1 on 2020-10-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20201007_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='info',
            field=models.CharField(max_length=100),
        ),
    ]
